[package]
edition = "2021"
name = "foonetic-macros"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0"
syn = "1.0"

[lib]
name = "foonetic_macros"
path = "src/lib.rs"
proc-macro = true
